Update github action

diff --git a/.github/workflows/dev-deploy.yml b/.github/workflows/dev-deploy.yml
--- a/.github/workflows/dev-deploy.yml
+++ b/.github/workflows/dev-deploy.yml
@@ -31,6 +31,7 @@ jobs:
         docker buildx build --platform linux/amd64 -t sast/sast-link -f docker/Dockerfile --output type=docker,dest=image.tar .
 
     - name: Deploy to Server
+      id: deploy
       uses: easingthemes/ssh-deploy@main
       with:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
@@ -40,8 +41,26 @@ jobs:
           REMOTE_USER: ${{ secrets.REMOTE_USER }}
           TARGET: /tmp/image.tar
           SCRIPT_AFTER: |
-            docker load -i tmp/image.tar
+            ### Notice: run for develop ###
+            # Stop and remove existing container if it exists
+            if [ "$(docker ps -aq -f name=sastlink)" ]; then
+              docker stop sastlink
+              docker rm sastlink
+            fi
+            # Remove existing image if it exists
+            if [ "$(docker images -q sast/sast-link)" ]; then
+              docker rmi sast/sast-link
+            fi
+            # Load the new image and run it
+            docker load -i ~/image.tar
             docker run -d --name sastlink -p 8080:8080 sast/sast-link
+
+    - name: Check Deployment Status
+      run: |
+        if [ "${{ steps.deploy.outcome }}" != "success" ]; then
+          echo "Deployment failed"
+          exit 1
+        fi
 
     - name: Send Success Message
       if: ${{ success() }}
